<?php
	require 'header.php';
	head("Contact");
?>

	<div class = "pad-c">
    	<div class="blurb">
    	    <center>
        	    <h2>Team Schedule</h2>
        		<p> This page is for our team members to see their schedules and important dates. </p>
    	    </center>
    	</div>
	</div>
	
	<table style=" width:98.5%" id = "schedule">
	    <tHead>
    	    <tr>
    	      <th colspan = "10" rowspan = "2">
    	          <p>2018 <i>FIRST</i>  Robotics Off Season Schedule</p>
    	      </th>
    	      <th colspan = "61">
    	          <p>2018</p>
    	      </th>
    	    </tr
    	   <tr>
              <!--<td colspan ="30">
                  <p>September</p>
    	      </td>
    	      <td colspan ="31">
                  <p>October</p>
              </td>-->
    	      <td colspan ="30">
                  <p>November</p>
    	      </td>
    	      <td colspan ="31">
                  <p>December</p>
                  
    	      </td>
    	      <!--<td colspan ="31">
    	          <p>January</p>
    	      </td>
    	      <td colspan ="28">
    	          <p>Febuary</p>
    	      </td>
    	      <td colspan ="31">
    	          <p>March</p>
    	      </td>
    	      <td colspan ="30">
    	          <p>April</p>
    	      </td>-->
    	   </tr>
	   </tHead>
	   <tbody>
    	   <tr id = "dayOfWeek">
              <td colspan = "10" id = "edge"></td>
              
    	      <!--<td><p>M</p>
    	      </td>
    	      <td>
    	          <p>T</p>
    	      </td>
    	      <td>
    	          <p>W</p>
    	      </td>-->
    	      <td>
    	          <p>R</p>
    	      </td>
    	      <td>
    	          <p>F</p>
    	      </td>
    	      <td>
    	          <b><p>S</p></b>
    	      </td>
    	      <td>
    	           <b><p>S</p></b>
    	      </td>
    	      <td>
    	          <p>M</p>
    	      </td>
    	      <td>
    	          <p>T</p>
    	      </td>
    	      <td>
    	          <p>W</p>
    	      </td>
    	      <td>
    	          <p>R</p>
    	      </td>
    	      <td>
    	          <p>F</p>
    	      </td>
    	      <td>
    	          <b><p>S</p></b>
    	      </td>
    	      <td>
    	           <b><p>S</p></b>
    	      </td>
    	      <td>
    	          <p>M</p>
    	      </td>
    	      <td>
    	          <p>T</p>
    	      </td>
    	      <td>
    	          <p>W</p>
    	      </td>
    	      <td>
    	          <p>R</p>
    	      </td>
    	      <td>
    	          <p>F</p>
    	      </td>
    	      <td>
    	          <b><p>S</p></b>
    	      </td>
    	      <td>
    	           <b><p>S</p></b>
    	      </td>
    	      <td>
    	          <p>M</p>
    	      </td>
    	      <td>
    	          <p>T</p>
    	      </td>
    	      <td>
    	          <p>W</p>
    	      </td>
    	      <td>
    	          <p>R</p>
    	      </td>
    	      <td>
    	          <p>F</p>
    	      </td>
    	      <td>
    	          <b><p>S</p></b>
    	      </td>
    	      <td>
    	           <b><p>S</p></b>
    	      </td>
    	      <td>
    	          <p>M</p>
    	      </td>
    	      <td>
    	          <p>T</p>
    	      </td>
    	      <td>
    	          <p>W</p>
    	      </td>
    	      <td>
    	          <p>R</p>
    	      </td>
    	      <td id= "newMonth">
    	          <p>F</p>
    	      </td>
    	      <td>
    	          <b><p>S</p></b>
    	      </td>
    	      <td>
    	           <b><p>S</p></b>
    	      </td>
    	      <td>
    	          <p>M</p>
    	      </td>
    	      <td>
    	          <p>T</p>
    	      </td>
    	      <td>
    	          <p>W</p>
    	      </td>
    	      <td>
    	          <p>R</p>
    	      </td>
    	      <td>
    	          <p>F</p>
    	      </td>
    	      <td>
    	          <b><p>S</p></b>
    	      </td>
    	      <td>
    	           <b><p>S</p></b>
    	      </td>
    	      <td>
    	          <p>M</p>
    	      </td>
    	      <td>
    	          <p>T</p>
    	      </td>
    	      <td>
    	          <p>W</p>
    	      </td>
    	      <td>
    	          <p>R</p>
    	      </td>
    	      <td>
    	          <p>F</p>
    	      </td>
    	      <td>
    	          <b><p>S</p></b>
    	      </td>
    	      <td>
    	           <b><p>S</p></b>
    	      </td>
    	      <td>
    	          <p>M</p>
    	      </td>
    	      <td>
    	          <p>T</p>
    	      </td>
    	      <td>
    	          <p>W</p>
    	      </td>
    	      <td>
    	          <p>R</p>
    	      </td>
    	      <td>
    	          <p>F</p>
    	      </td>
    	      <td>
    	          <b><p>S</p></b>
    	      </td>
    	      <td>
    	          <b><p>S</p></b>
    	      </td>
    	      <td>
    	          <p>M</p>
    	      </td>
    	      <td>
    	          <p>T</p>
    	      </td>
    	      <td>
    	          <p>W</p>
    	      </td>
    	      <td>
    	          <p>R</p>
    	      </td>
    	      <td>
    	          <p>F</p>
    	      </td>
    	     
    	      <td>
    	          <b><p>S</p></b>
    	      </td>
    	      <td>
    	          <b><p>S</p></b>
    	      </td>
    	      <td id= "newMonth">
    	          <p>M</p>
    	      </td>
    	      <!--<td>
    	          <p>T</p>
    	      </td>
    	      <td>
    	          <p>W</p>
    	      </td>
    	      <td>
    	          <p>TH</p>
    	      </td>
    	      <td>
    	          <p>F</p>
    	      </td>
    	      <td>
    	          <b><p>S</p></b>
    	      </td>
    	      <td>
    	          <b><p>S</p></b>
    	      </td>
    	      <td>
    	          <p>M</p>
    	      </td>
    	      <td>
    	          <p>T</p>
    	      </td>
    	      <td>
    	          <p>W</p>
    	      </td>
    	      <td>
    	          <p>TH</p>
    	      </td>
    	      <td>
    	          <p>F</p>
    	      </td>
    	      <td>
    	          <b><p>S</p></b>
    	      </td>
    	      <td>
    	          <b><p>S</p></b>
    	      </td>-->
    	    </tr>
           <tr id = "dayOfMonth">
               <td colspan = "10" id= "edge"style = "letter-spacing: 0"><p style = "font-family: roboto"><b>Tasks/Events</b></p></td>
	           <td>
	               <p>1</p>
	           </td>
	           <td>
	               <p>2</p>
	           </td>
	           <td>
	               <P>3</P>
	           </td>
	           <td>
	               <P>4</P>
	           </td>
	           <td>
	               <P>5</P>
	           </td>
	           <td>
	               <P>6</P>
	           </td>
	           <td>
	               <P>7</P>
	           </td>
	           <td>
	               <P>8</P>
	           </td>
	           <td>
	               <P>9</P>
	           </td>
	           <td>
	               <P>10</P>
	           </td>
	           <td>
	               <P>11</P>
	           </td>
	           <td>
	               <P>12</P>
	           </td>
	           <td>
	               <P>13</P>
	           </td>
	           <td>
	               <P>14</P>
	           </td>
	           <td>
	               <P>15</P>
	           </td>
	           <td>
	               <P>16</P>
	           </td>
	           <td>
	               <P>17</P>
	           </td>
	           <td>
	               <P>18</P>
	           </td>
	           <td>
	               <P>19</P>
	           </td>
	           <td>
	               <P>20</P>
	           </td>
	           <td>
	               <P>21</P>
	           </td>
	           <td>
	               <P>22</P>
	           </td>
	           <td>
	               <P>23</P>
	           </td>
	           <td>
	               <P>24</P>
	           </td>
	           <td>
	               <P>25</P>
	           </td>
	           <td>
	               <P>26</P>
	           </td>
	           <td>
	               <P>27</P>
	           </td>
	           <td>
	               <P>28</P>
	           </td>
	           <td>
	               <P>29</P>
	           </td>
	           <td id= "newMonth">
	               <P>30</P>
	           </td>
	           <!--<td>
	               <P>31</P>
	           </td>-->
	           <td>
	               <P>1</P>
	           </td>
	           <td>
	               <p>2</p>
	           </td>
	           <td>
	               <P>3</P>
	           </td>
	           <td>
	               <P>4</P>
	           </td>
	           <td>
	               <P>5</P>
	           </td>
	           <td>
	               <P>6</P>
	           </td>
	           <td>
	               <P>7</P>
	           </td>
	           <td>
	               <P>8</P>
	           </td>
	           <td>
	               <P>9</P>
	           </td>
	           <td>
	               <P>10</P>
	           </td>
	           <td>
	               <P>11</P>
	           </td>
	           <td>
	               <P>12</P>
	           </td>
	           <td>
	               <P>13</P>
	           </td>
	           <td>
	               <P>14</P>
	           </td>
	           <td>
	               <P>15</P>
	           </td>
	           <td>
	               <P>16</P>
	           </td>
	           <td>
	               <P>17</P>
	           </td>
	           <td>
	               <P>18</P>
	           </td>
	           <td>
	               <P>19</P>
	           </td>
	           <td>
	               <P>20</P>
	           </td>
	           <td>
	               <P>21</P>
	           </td>
	           <td>
	               <P>22</P>
	           </td>
	           <td>
	               <P>23</P>
	           </td>
	           <td>
	               <P>24</P>
	           </td>
	           <td>
	               <P>25</P>
	           </td>
	           <td>
	               <P>26</P>
	           </td>
	           <td>
	               <P>27</P>
	           </td>
	           <td>
	               <P>28</P>
	           </td>
	           <td>
	               <P>29</P>
	           </td>
	           <td>
	               <P>30</P>
	           </td>
	           <td id= "newMonth">
	               <p>31</p>
	           </td>
	       </tr>
	   </tbody>
	   <tfoot>  
            <div class = "cells">
             <!--<tr>
    	       <td colspan = "10" id= "title"><p><b>Fall Fiesta</b></p></td>
    	       <td>
    	               <p></p>
    	       </td>
    	           <td>
    	               <p></p>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td id = "red">
    	               <P></P>
    	       </td>
    	           <td id = "red">
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <p></p>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	           </td>
            </tr>-->
             <!--<tr>
    	       <td colspan = "10" id= "title"><p>Drive Team Interviews</p></td>
    	       <td>
    	           <p></p>
    	       </td>
    	       <td>
    	           <p></p>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	            <P></P>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <p></p>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
            </tr>-->
             <tr>
    	       <td colspan = "10" id= "title"><p>Admin</p></td>
    	       <td>
    	               <p></p>
    	       </td>
    	       <td>
    	           <p></p>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td> 
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	           <p></p>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	     </tr>
             <tr>
    	       <td colspan = "10"><p style = "font-weigth= normal">Team Meetings</p></td>
    	     	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <P></P>
    	       </td>
    	       <td>
    	               <p></p>
    	       </td>
    	           <td id = "red">
    	               <p></p>
    	       </td>
    	           <td id = "red">
    	               <P></P>
    	       </td>
    	           <td id = "red">
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td id = "red">
    	               <P></P>
    	       </td>
    	           <td id = "red">
    	               <P></P>
    	       </td>
    	           <td id = "red">
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td id = "red">
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td id = "red">
    	               <P></P>
    	       </td>
    	           <td id = "red">
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td id = "red">
    	               <P></P>
    	           </td>
    	           <td id = "red">
    	               <P></P>
    	           </td>
    	           <td>
    	               <p></p>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td id = "red">
    	               <P></P>
    	           </td>
    	           <td id = "red">
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	           </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	           <td>
    	               <P></P>
    	       </td>
    	        <td>
    	               <P></P>
    	       </td>
            </tr>
             <tr>
    	       <td colspan = "10" id= "title"><p>Programming</p></td>
    	      <td>
    	               <p></p>
    	       </td>
    	       <td>
    	               <p></p>
    	       </td>
    	       <td>
    	               <p></p>
    	       </td>
    	       <td>
    	               <p></p>
    	       </td>
    	       <td>
    	               <p></p>
    	       </td>
    	       <td>
    	           <p></p>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <p></p>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	     </tr>
             <!--<tr>
    	       <td colspan = "10" id= "title"><p>Chassis Code</p></td>
    	       <td>
    	           <p></p>
    	       </td>
    	       <td>
    	           <p></p>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <p></p>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "blue">
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	     </tr>-->
    	     <tr>
    	       <td colspan = "10" id= "title"><p>Website Updates</p></td>
    	     <td>
    	               <p></p>
    	       </td>
    	       <td>
    	               <p></p>
    	       </td>
    	       <td>
    	               <p></p>
    	       </td>
    	       <td>
    	               <p></p>
    	       </td>
    	       <td>
    	               <p></p>
    	       </td>
    	       <td>
    	           <p></p>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <p></p>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	     </tr>
    	     <tr>
    	       <td colspan = "10" id= "title"><p>Social Media Posts</p></td>
    	       <td>
    	               <p></p>
    	       </td>
    	       <td>
    	           <p></p>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id ="red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id ="red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id ="red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id ="red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id ="red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id ="red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <p></p>
    	       </td>
    	       <td id = "red">
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	     </tr>
    	     <tr>
    	       <td colspan = "10" id= "title"><p></p></td>
    	       <td>
    	               <p></p>
    	       </td>
    	       <td>
    	           <p></p>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <p></p>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	       <td>
    	           <P></P>
    	       </td>
    	     </tr>
	       </tfoot>
	       
	        </div>
       </tfoot>
    </table div>
    
    	<table id = "legend">
	    <tr id = "ltitle">
	        <td colspan = "2"><p><b>Legend</b></p></td>
	    </tr>
	    <tr>
	       <td id ="red"></td>
	       <td><p>Hard Deadlines /Events</p></td> 
	    </tr>
	    <tr>
	        <td id ="blue"></td> 
	        <td>Scheduled Work Days</td> 
	    </tr>
	</table>
	
<?php
    require 'footer.php';
?>